Update linux-continue-v2

diff --git a/linux-continue-v2 b/linux-continue-v2
--- a/linux-continue-v2
+++ b/linux-continue-v2
@@ -82,9 +82,22 @@ Promt for input --->
 #!/bin/bash
                                          [Asks for the user to input data, it prints out your name is "name"]
                                          Read options: -r [Backslash is not an escape character],
-                                                       -t [Time out if reading from stdin], 
+                                                       -t [Time out if reading from stdin],
                                                        -s [Don't echo typed characters]
 read -p "What's is your name" username
 echo "Your name is $username"
 -------------------------------------
+Process shell options -->
+--------------EXAMPLE----------------
+script name: getops.sh
 
+while getopts ":a:" opt; do
+      case $opt in
+            a) echo "You passed the -a option with the $OPTARG argument" >&2 ;;
+            :) echo "Option $opt requires an argument" >&2 ; exit 1 ;;
+           /?) echo "Invalid option: -$opt" > &2 ;;
+      esac
+done
+shift $((OPTIND-1))
+echo '$1 is' "$1"
+-------------------------------------
